Class IHE.Msg.CDA.Common.Patient Extends (%RegisteredObject, %XML.Adaptor) [ Language = objectscript ]
{

/// 身份证号
Property IDCardNo As %String;

/// 患者姓名
Property PatientName As %String;

/// 性别代码
Property GenderCode As %String;

/// 性别名称
Property GenderName As %String;

/// 婚姻状况代码
Property MarriageCode As %String;

/// 婚姻状况名称
Property MarriageName As %String;

/// 民族代码
Property NationCode As %String;

/// 民族名称
Property NationName As %String;

/// 国籍代码
Property NationalityCode As %String;

/// 国籍名称
Property NationalityName As %String;

/// 职业代码
Property OccupationCode As %String;

/// 职业名称
Property OccupationName As %String;

/// 出生日期
Property BirthTime As %String;

/// 年龄
Property Age As %String;

}
