Class IHE.Msg.CDA.Common.RelatedOrgan Extends (%RegisteredObject, %XML.Adaptor) [ Language = objectscript ]
{

/// 病床号
Property BedCode As %String;

/// 病床名称
Property BedName As %String;

/// 病房号
Property RoomCode As %String;

/// 病房名称
Property RoomName As %String;

/// 科室代码
Property DeptCode As %String;

/// 科室名称
Property DeptName As %String;

/// 病区代码
Property AreaCode As %String;

/// 病区名称
Property AreaName As %String;

/// 医院代码
Property OrganCode As %String;

/// 医院名称
Property OrganName As %String;

}
