Class IHE.Msg.CDA.C0034ChineseDiag Extends (%RegisteredObject, %XML.Adaptor) [ Language = objectscript ]
{

/// 中医诊断日期
Property Time As %String;

/// 中医诊断疾病名称
Property Value As %String;

/// 中医诊断代码
Property Code As %String;

/// 中医诊断名称
Property Name As %String;

/// 中医证候病名
Property SymptomValue As %String;

/// 中医证候代码
Property SymptomCode As %String;

/// 中医证候名称
Property SymptomName As %String;

/// 中医入院诊断顺位
Property AdmSequence As %String;

}
